// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Metadata holds the result of spreadsheets.get + drive.files.get.
 */
export class Metadata {
    /**
     * Creates a new Metadata instance.
     * @param {Partial<Metadata>} [$$source = {}] - The source object to create the Metadata.
     */
    constructor($$source = {}) {
        if (!("SpreadsheetID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["SpreadsheetID"] = "";
        }
        if (!("Title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Title"] = "";
        }
        if (!("Tabs" in $$source)) {
            /**
             * @member
             * @type {Tab[]}
             */
            this["Tabs"] = [];
        }
        if (!("Version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Version"] = "";
        }
        if (!("ModifiedTime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ModifiedTime"] = "";
        }
        if (!("Visibility" in $$source)) {
            /**
             * "public" | "link-only" | "private" | "unknown"
             * @member
             * @type {string}
             */
            this["Visibility"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Metadata instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Metadata}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Tabs" in $$parsedSource) {
            $$parsedSource["Tabs"] = $$createField2_0($$parsedSource["Tabs"]);
        }
        return new Metadata(/** @type {Partial<Metadata>} */($$parsedSource));
    }
}

/**
 * Tab represents a sheet tab within a spreadsheet.
 */
export class Tab {
    /**
     * Creates a new Tab instance.
     * @param {Partial<Tab>} [$$source = {}] - The source object to create the Tab.
     */
    constructor($$source = {}) {
        if (!("TabID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["TabID"] = 0;
        }
        if (!("Title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Title"] = "";
        }
        if (!("Idx" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Idx"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Tab instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Tab}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Tab(/** @type {Partial<Tab>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Tab.createFrom;
const $$createType1 = $Create.Array($$createType0);
