// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Metadata holds the result of spreadsheets.get + drive.files.get.
 */
export interface Metadata {
    "SpreadsheetID": string;
    "Title": string;
    "Tabs": Tab[] | null;
    "Version": string;
    "ModifiedTime": string;

    /**
     * "public" | "link-only" | "private" | "unknown"
     */
    "Visibility": string;
}

/**
 * Tab represents a sheet tab within a spreadsheet.
 */
export interface Tab {
    "SheetID": number;
    "Title": string;
    "Idx": number;
}
