// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Spreadsheet {
    /**
     * Creates a new Spreadsheet instance.
     * @param {Partial<Spreadsheet>} [$$source = {}] - The source object to create the Spreadsheet.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }
        if (!("GoogleID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["GoogleID"] = "";
        }
        if (!("Title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Title"] = "";
        }
        if (!("URL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["URL"] = "";
        }
        if (!("Notes" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Notes"] = "";
        }
        if (!("Version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Version"] = "";
        }
        if (!("ModifiedTime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ModifiedTime"] = "";
        }
        if (!("Visibility" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Visibility"] = "";
        }
        if (!("IsTracked" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["IsTracked"] = false;
        }
        if (!("LastScanAt" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["LastScanAt"] = null;
        }
        if (!("AddedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["AddedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Spreadsheet instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Spreadsheet}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Spreadsheet(/** @type {Partial<Spreadsheet>} */($$parsedSource));
    }
}
