// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Spreadsheet {
    "ID": number;
    "GoogleID": string;
    "Title": string;
    "URL": string;
    "Notes": string;
    "Version": string;
    "ModifiedTime": string;
    "Visibility": string;
    "IsTracked": boolean;
    "LastScanAt": string | null;
    "AddedAt": string;
}

export interface Tab {
    "ID": number;
    "SpreadsheetID": number;
    "TabID": number;
    "Title": string;
    "Idx": number;
}

/**
 * TriggeredBy records what kicked off a scan run.
 * CHECK (manual, launch, add) in migrations/0001_init.sql.
 */
export enum TriggeredBy {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TriggerManual = "manual",
    TriggerLaunch = "launch",
    TriggerAdd = "add",
};
