// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Spreadsheet {
    "ID": number;
    "GoogleID": string;
    "Title": string;
    "URL": string;
    "Notes": string;
    "Version": string;
    "ModifiedTime": string;
    "Visibility": string;
    "IsTracked": boolean;
    "LastScanAt": string | null;
    "AddedAt": string;
}
