// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AccountInfo {
    /**
     * Creates a new AccountInfo instance.
     * @param {Partial<AccountInfo>} [$$source = {}] - The source object to create the AccountInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email"] = "";
        }
        if (!("photo_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["photo_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccountInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AccountInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccountInfo(/** @type {Partial<AccountInfo>} */($$parsedSource));
    }
}

/**
 * AuthState is mirrored to the frontend via the "auth:state" event.
 */
export class AuthState {
    /**
     * Creates a new AuthState instance.
     * @param {Partial<AuthState>} [$$source = {}] - The source object to create the AuthState.
     */
    constructor($$source = {}) {
        if (!("connected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["connected"] = false;
        }
        if (!("status" in $$source)) {
            /**
             * disconnected | connecting | connected | expired
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["message"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuthState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AuthState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AuthState(/** @type {Partial<AuthState>} */($$parsedSource));
    }
}
