// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AuthState is mirrored to the frontend via the "auth:state" event.
 */
export interface AuthState {
    "connected": boolean;

    /**
     * disconnected | connecting | connected | expired
     */
    "status": string;
    "message"?: string;
}
