// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../db/models.js";

export interface AccountInfo {
    "name": string;
    "email": string;
    "photo_url": string;
}

/**
 * AuthState is mirrored to the frontend via the "auth:state" event.
 */
export interface AuthState {
    "connected": boolean;

    /**
     * disconnected | connecting | connected | expired
     */
    "status": string;
    "message"?: string;
}

export interface DbMetadata {
    "SpreadsheetID": string;
    "Title": string;
    "Tabs": db$0.Tab[] | null;
    "Version": string;
    "ModifiedTime": string;
    "Visibility": string;
}

/**
 * ScanResult holds all tab results for a spreadsheet.
 */
export interface ScanResult {
    "spreadsheetId": string;
    "title": string;
    "tabs": TabResult[] | null;
}

/**
 * TabResult holds the raw BatchGet response for one tab.
 */
export interface TabResult {
    "tabName": string;
    "tabId": number;
    "range": string;
    "values": (any[] | null)[] | null;
}
