// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../db/models.js";

export interface AccountInfo {
    "name": string;
    "email": string;
    "photo_url": string;
}

/**
 * AuthState is mirrored to the frontend via the "auth:state" event.
 */
export interface AuthState {
    "connected": boolean;

    /**
     * disconnected | connecting | connected | expired
     */
    "status": string;
    "message"?: string;
}

export interface DbMetadata {
    "SpreadsheetID": string;
    "Title": string;
    "Tabs": db$0.Tab[] | null;
    "Version": string;
    "ModifiedTime": string;
    "Visibility": string;
}

export interface ScanSummary {
    "spreadsheetId": string;
    "title": string;
    "tabsScanned": number;
    "edgesFound": number;
}
