// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * OAuthService exposes Google account connection to the frontend. It is a
 * Wails-bound service: the only place that touches app events / the browser.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Returns user account info (name, email)
 * @returns {$CancellablePromise<$models.AccountInfo>}
 */
export function Account() {
    return $Call.ByID(429884205).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Connect starts the browser consent flow. It returns immediately; the
 * outcome arrives through the "auth:state" event. Concurrent calls while a
 * flow is in progress are ignored and just echo the connecting state.
 * @returns {$CancellablePromise<$models.AuthState | null>}
 */
export function Connect() {
    return $Call.ByID(2183435296).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Disconnect removes the stored tokens.
 * @returns {$CancellablePromise<void>}
 */
export function Disconnect() {
    return $Call.ByID(3310349636);
}

/**
 * Status reports the current connection state. It validates and silently
 * refreshes a stored token so a returning user reconnects without the browser.
 * @returns {$CancellablePromise<$models.AuthState | null>}
 */
export function Status() {
    return $Call.ByID(2974597324).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.AccountInfo.createFrom;
const $$createType1 = $models.AuthState.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
