// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * OAuthService exposes Google account connection to the frontend. It is a
 * Wails-bound service: the only place that touches app events / the browser.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Returns user account info (name, email)
 */
export function Account(): $CancellablePromise<$models.AccountInfo> {
    return $Call.ByID(429884205);
}

/**
 * Connect starts the browser consent flow. It returns immediately; the
 * outcome arrives through the "auth:state" event. Concurrent calls while a
 * flow is in progress are ignored and just echo the connecting state.
 */
export function Connect(): $CancellablePromise<$models.AuthState | null> {
    return $Call.ByID(2183435296);
}

/**
 * Disconnect removes the stored tokens.
 */
export function Disconnect(): $CancellablePromise<void> {
    return $Call.ByID(3310349636);
}

/**
 * Status reports the current connection state. It validates and silently
 * refreshes a stored token so a returning user reconnects without the browser.
 */
export function Status(): $CancellablePromise<$models.AuthState | null> {
    return $Call.ByID(2974597324);
}
