// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ScanService orchestrates formula scanning of tracked spreadsheets.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ScanSpreadsheet fetches formula data from all tabs of a spreadsheet.
 * Returns raw cell values so we can inspect the BatchGet response structure.
 */
export function ScanSpreadsheet(spreadsheetID: number): $CancellablePromise<$models.ScanResult | null> {
    return $Call.ByID(1279636441, spreadsheetID);
}
