// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SheetsService exposes spreadsheet management to the frontend. It is a
 * Wails-bound service.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../db/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sheets$0 from "../sheets/models.js";

/**
 * Add fetches metadata for the given Google Sheets URL, persists it, and
 * returns the saved spreadsheet. Returns an error with "no access / not found"
 * if Drive returns 404.
 * @param {string} url
 * @param {string} notes
 * @returns {$CancellablePromise<db$0.Spreadsheet | null>}
 */
export function Add(url, notes) {
    return $Call.ByID(3167858916, url, notes).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * FetchMetadata is a thin wrapper for testing — calls the Google API directly.
 * @param {string} spreadsheetID
 * @returns {$CancellablePromise<sheets$0.Metadata | null>}
 */
export function FetchMetadata(spreadsheetID) {
    return $Call.ByID(1159559758, spreadsheetID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * List returns all tracked spreadsheets.
 * @returns {$CancellablePromise<db$0.Spreadsheet[]>}
 */
export function List() {
    return $Call.ByID(3118029841).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * Remove deletes a spreadsheet and its tabs.
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function Remove(id) {
    return $Call.ByID(1012070221, id);
}

// Private type creation functions
const $$createType0 = db$0.Spreadsheet.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = sheets$0.Metadata.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType0);
