// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SheetsService exposes spreadsheet management to the frontend. It is a
 * Wails-bound service.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../db/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Add fetches metadata for the given Google Sheets URL, persists it, and
 * returns the saved spreadsheet. Returns an error with "no access / not found"
 * if Drive returns 404.
 */
export function Add(url: string, notes: string): $CancellablePromise<db$0.Spreadsheet | null> {
    return $Call.ByID(3167858916, url, notes);
}

/**
 * FetchDbMetadata returns spreadsheet metadata from the database.
 */
export function FetchDbMetadata(spreadsheetID: number): $CancellablePromise<$models.DbMetadata | null> {
    return $Call.ByID(314275568, spreadsheetID);
}

/**
 * List returns all tracked spreadsheets.
 */
export function List(): $CancellablePromise<db$0.Spreadsheet[] | null> {
    return $Call.ByID(3118029841);
}

/**
 * Remove deletes a spreadsheet and its tabs.
 */
export function Remove(id: number): $CancellablePromise<void> {
    return $Call.ByID(1012070221, id);
}
